# Graphen

Ein Graph ist ein Abstrakter Datentyp. Mathematisch wird ein Graph $G$ durch ein geordnetes Paar $(V, E)$ beschrieben. $V$ Ist dabei die Menge der Knoten (Vertices, Sg. Vertex) und $E$ die Menge der Kanten (Edges), die die Knoten verbinden. Eine Kante ist dabei ein geordnetes Parr $(i, j)$, wobei mit $i$ und $j$ zwei Knoten angegeben werden, die durch die Kante verbunden werden. 

Bei der Darstellung eines Graphen spielt die Art und Weise, wie die Kanten gezeichnet werden keine Rolle. Entscheidend ist lediglich die Menge der Knoten und die Menge der Kanten, die diese verbinden. Zwei unterschiedlich dargestellte Graphen mit den gleichen Knoten und Kanten werden als isomorphe Graphen bezeichnet. In der Regel betrachtet man isomorphe Graphen als äquivalente Graphen.

In der Praxis kommen Graphen häufig zum Einsatz. Die Abbildung von Straßennetzen in Navigationssystemen oder die Abbildung von Netzwerken in Routern sind Anwendungsbeispiele.

## Ungerichteter Graph

Bei einem ungerichteten Graphen wird die Richtung der Kante nicht berücksichtigt, d.h. eine Kante $(i, j)$ impliziert einen Weg vom Knoten $i$ zum $j$, als auch einen Weg von $j$ zu $i$. Somit gilt $(i, j) = (j, i)$.

Ungerichteter Graph mit $V = \{0,1,2,3,4\}$ und $E = \{(0,1),(0,4),(1,2),(1,3),(1,4),(2,3),(3,4)\}$:

<img src="https://www.geeksforgeeks.org/wp-content/uploads/undirectedgraph.png" width="400">

Bei der Darstellung eines ungerichteten Graphen ist es deshalb nicht nötig Pfeile zu verwenden.

## Gerichteter Graph

Bei einem gerichteten Graphen wird die Richtung der Kante berücksichtigt. Ist eine Kante $(i, j)$ gegeben, so verläuft ein Weg von $i$ zu $j$, jedoch nicht zwangsläufig von $j$ zu $i$.

Gerichteter Graph mit $V = \{A,B,C,D,E,F\}$ und $E = \{(A,B),(B,C),(C,E),(D,B),(E,D),(E,F)\}$:

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Directed_graph%2C_cyclic.svg/2000px-Directed_graph%2C_cyclic.svg.png" width="250">

Bei der Darstellung eines gerichteten Graphen werden Pfeile verwendet, um die Richtung einer Kante anzugeben. 

Da eine Kante in einem $(i, j)$ in einem ungerichteten Graph durch die beiden Kanten $(i, j)$ und $(j, i)$ eine gerichteten Graphen dargestellte werden kann, kann jeder ungerichtete Graph als gerichteter Graph beschrieben werden. Die Umkehrung gilt nicht.

## Gewichteter Graph

Bei einem gewichteten Graphen wird jeder Kante ein numerischer Wert als Gewicht zugeordnet.

Dies ist beispielsweise nützlich, um ein Straßennetz abzubilden und mit den Gewichten die Distanz zwischen Knotenpunkten anzugeben. Die Gewichte können dabei jegliche Art von Kosten darstellen, bei einem Navigationssystem könnten auch die benötigte Zeit oder der Benzinverbrauch durch die Gewichte abgebildet werden.

Ein gewichteter Graph kann sowohl gerichtetet, als auch ungerichtet sein.

<img src="https://www.geeksforgeeks.org/wp-content/uploads/graph-STL.png" width="250">

## Adjazenzmatrix

Die Adjazenzmatrix ist eine Variante, um einen Graphen zu implementieren. Dabei wird eine quadratische Matrix erstellt, bei denen eine Spalte und eine Reihe jeweils für einen Knoten steht. Im entsprechenden Feld steht das Gewicht der Kante vom Spaltenknoten zum Reihenknoten. Existiert eine Kante nicht, so wird ein Ersatzwert, wie $\infty$ oder __null__ verwendet. Handelt es sich um einen ungewichteten Graphen, so können auch booleans verwendet werden.

Der Graph
<img src="https://www.geeksforgeeks.org/wp-content/uploads/graph-STL.png" width="250">
wird dabei folgendermaßen dargestellt:

$$
\begin{bmatrix}
0 & 10 & 3 & 2 \\
\infty & 0 & \infty & 7 \\
\infty & \infty & 0 & 6 \\
\infty & \infty & \infty & 0 \\
\end{bmatrix}
$$

Da es sich um eine quadratische Matrix handelt beträgt der Speicheraufwand $\mathcal{O}({\lvert V \rvert}^2)$.

Ineffzient ist die Adjazenzmatrix, wenn der Graph nur wenige Kanten besitzt, da trotzdem Werte für jede mögliche Kante gespeichert werden müssen, nämlich $\infty$.

## Adjazenzliste

Eine alternative Implementation eines Graphen ist die Adjazenzliste. Hierbei wird bei jedem Knoten $v$ in einer Liste eingetragen, zu welchen anderen Knoten der Knoten $v$ adjazent ist, d.h. zu welchen Knoten es eine Kante ausgehend vom Knoten $v$ gibt. Handelt es sich um einen gewichteten Graphen, so handelt es sich bei der Adjazenzliste an Stelle einer Liste von Knoten um eine Liste von Paaren von Knoten und Gewichten.

Handelt es sich um einen Graphen mit wenigen Kanten, so wird weniger Speicherplatz verbraucht, da lediglich für die Kanten, die existieren, Speicher beansprucht werden muss. Die worst-case Speicherkomplexität beträgt wieterhin $\mathcal{O}({\lvert V \rvert}^2)$, da es bis zu $\lvert V \rvert \cdot \left( \lvert V \rvert - 1 \right) \in \mathcal{O}({\lvert V \rvert}^2)$ Kanten geben kann.

In [160]:
class Node:
    def __init__(self, name):
        self.name = name
        self.adj = []
        
    def add_to_adj_lst(self, node, weight=1):
        self.adj.append((node, weight))
    

v0 = Node('0')
v1 = Node('1')
v2 = Node('2')
v3 = Node('3')

v0.add_to_adj_lst(v1, 10)
v0.add_to_adj_lst(v2, 3)
v0.add_to_adj_lst(v3, 2)
v1.add_to_adj_lst(v3, 7)
v2.add_to_adj_lst(v3, 6)

## Depth-First Search

Depth-First Search (Tiefensuche) ist ein Algorithmus, um einen Knoten in einem Graphen zu finden. Dabei wird von einem Startknoten aus rekursiv immer auf den zum Starknoten adjazenten Knoten die Tiefensuche aufgerufen. Dadurch, dass der rekursive Aufruf immer auf dem nächsten Knoten erfolgt, wird zuerst in die Tiefe gegangen, dehalb der Begriff Tiefensuche bzw. Depth-First Search. Es wird solange in die Tiefe gegangen, bis ein Knoten erreicht ist, der keine adjazenten Knoten hat. Daraufhin folgt der nächste Aufruf auf einer Rekursionsebene höher. Es wird also quasi wieder ein Schritt zurückgegangen, nämlich zu dem Punkt, wo die nächste Entscheidungsmöglichkeit stattfindet. Diesen Vorgang nennt man Backtracking.

__Implementation mit folgendem Beispiel:__

<img src="https://ds055uzetaobb.cloudfront.net/image_optimizer/78fb8725fb8db65ecbc1a7e0765f48e4f4ccb30f.png" width="250">

In [161]:
def dfs(root):
    print(root.name, end=' ')
    for node in root.adj:
        dfs(node[0])
    

a = Node('A')
b = Node('B')
c = Node('C')
d = Node('D')
e = Node('E')
f = Node('F')
g = Node('G')

a.add_to_adj_lst(b)
b.add_to_adj_lst(c)
b.add_to_adj_lst(e)
b.add_to_adj_lst(d)
c.add_to_adj_lst(e)
d.add_to_adj_lst(e)
e.add_to_adj_lst(f)
g.add_to_adj_lst(d)

dfs(a)

A B C E F E F D E F 

Es werden alle von A aus erreichbaren Knoten ausgegeben, entsprechend der Reihenfolge von DFS. 

Der Knoten G taucht nicht auf, da er von A aus nicht erreichbar ist.

Da es mehrere Wege zu einem Knoten gibt, kommen Knoten mehrfach vor. Handelt es sich um einen Graph mit Kreisen, so würde der Algorithmus nicht terminieren. Um dies zu verhindern, kann man in einem Dictionary die bereits gefundenen Knoten speichern und nur weitersuchen, wenn es sich um einen Knoten handelt, der noch nicht gefunden wurde.

In [162]:
def dfs_no_dupl(root, found={}):
    if root not in found:
        print(root.name, end=' ')
        found[root] = True
        for node in root.adj:
            dfs_no_dupl(node[0], found)
        
    
dfs_no_dupl(a)

A B C E F D 

Da jeder Knoten und jede Kante jeweils maximal einmal besucht werden, beträgt die Laufzeit $\mathcal{O}(\lvert V \rvert + \lvert E \rvert)$.

__Beispiele__

### 0/1 Rucksackproblem

Beim Rucksackproblem ist eine nichtleere Menge von $n$ Gegenstanden mit den Gewichten $w_1, w_2, \dotsc, w_n$ mit $w_i > 0$ und den zugehorigen Werten $v_1, v_2, \dotsc, v_n$ gegeben. Das Gewicht des $i$-ten Gegenstands beträgt $w_i$, sein Wert $v_i$. Die Interpretation des Wertes wird durch den jeweiligen Sachkontext bestimmt: Denkt man an Schmuck, so kann der Wert im potenziellen Verkaufserlos bestehen. Handelt es sich um Utensilien eines Bergwanderes, richtet sich der Wert eines Gegenstandes eher nach dessen Beitrag zur Absicherung einer unfallfreien Begehung. Der Rucksack ist nur beschränkt belastbar. Das zulässige Maximalgewicht sei $K$, d.h. das aktuelle Gesamtgewicht darf $K$ keinesfalls überschreiten. Zu beachten ist, dass beim 0/1 Rucksackproblem, im Gegansatz zum Bruchteil-Rucksackproblem, ein Gegenstand entweder in den Rucksack gepackt werden kann oder nicht, eine Teilung des Gegenstands ist hierbei nicht möglich.

Die Optimierungsaufgabe besteht nun darin, einen Rucksack so zu füllen, dass die Wertsumme der eingepackten Gegenstände – unter Beachtung seiner Kapazitätsschranke – maximal ist.

Zum Finden der Lösungen dieses Problems unter der Nutzung der Tiefensuche, muss ein Entscheidungsbaum aufgestellt werden. Dieser Entscheidungsbaum hat dabei die Höhe $n$ ($n$ = Anzahl der Gegenstände). In jedem Schritt gibt es zwei Entscheidungsmöglichkeiten, entweder der $i$-te Gegenstand wird in den Rucksack gepackt oder nicht. Durch diesen Entscheidungsbaum werden alle Kombinationen der Rucksackbefüllung konstruiert.

---
Grafik hier einfügen

---

Die Tiefensuche kann nun genutzt werden, um alle gültigen Rucksackbefüllungen zu finden. Dabei wird rekursiv auf die beiden Entscheidungsmöglichkeiten die Tiefensuche aufgerufen.

Das es sich um einen Binärbaum handelt, beträgt die Anzahl Bätter $2^n$. Insgesamt besteht der Baum aus $\sum_{i=0}^n 2^i = 2^{n+1} - 1 \in \mathcal{O}(2^n)$ Knoten, wodurch die Laufzeit des Algorithmus $\mathcal{O}(2^n)$ beträgt.

Ein Optimierung ist es, im Falle, dass ein Legen des Gegenstand in den Rucksack zu einer Überschreitung des Maximalgewichts $K$ führt, nicht weiter zu expandieren. Da $w_i > 0$ gilt, werden auch alle weiteren Kombination das Maximalgewicht überschreiten.

In [163]:
def get_solutions(items, k, knapsack=[]):
    if len(items) == 0:
        return [list(knapsack)]
    if items[0][0] <= k:
        return get_solutions(items[1:], k - items[0][0], knapsack + [items[0]]) + get_solutions(items[1:], k, knapsack)
    return get_solutions(items[1:], k, knapsack)


K = 60
items = [(50, 30), (30, 20), (10, 25)]

print(get_solutions(items, K))

[[(50, 30), (10, 25)], [(50, 30)], [(30, 20), (10, 25)], [(30, 20)], [(10, 25)], []]


Interessiert man sich nur für die optimale Lösung, so kann der Code so abgeändert werden, dass der Wert der gefunden gültigen Rucksackbefüllung mit dem bisher gefundenen Wert verglichen wird und im Fall, dass ein besserer Wert erreicht wurde, der bisherige Wert durch die neu gefundene Lösung ersetzt wird.

In [164]:
#helper function to get value of a knapsack
def value(knapsack):
    sum_value = 0
    for item in knapsack:
        sum_value += item[1]
    return sum_value


def get_optimal_solution(items, k, knapsack=[]):
    if len(items) == 0:
        return knapsack
    if items[0][0] <= k:
        solution_with = get_optimal_solution(items[1:], k - items[0][0], knapsack + [items[0]])
        solution_without = get_optimal_solution(items[1:], k, knapsack)
        if value(solution_without) > value(solution_with):
            return solution_without
        return solution_with
    return get_optimal_solution(items[1:], k, knapsack)


print(get_optimal_solution(items, K))

[(50, 30), (10, 25)]


### n-Damenproblem

Das $n$-Damenproblem ist ein schachmathematisches Problem und eine Verallgemeinerung des 8-Damenproblems.

Ziel beim 8-Damenproblem ist es, 8 Damen auf einem 8x8 Schachbrett so zu platzieren, dass keine Dame gemäß den Schachregeln eine andere Dame schlagen kann. Dies bedeutet, dass keine zwei Damen auf der selben Reihe, Linie (Zeile, Spalte) oder Diagonale stehen darf.

Eine Lösung für das 8-Dameproblem ist die folgende:

<img src="http://schinckel.net/images/2008/06/8queens.jpg" width="250">

Beim $n$-Damenproblem ist es entsprechend Ziel $n$ Damen auf einem $n$x$n$ Schachbrett zu platzieren.

Für dieses Problem kann ebenfalls rekursives Backtracking, also Depth-First Search, zum Lösen genutzt werden. 

Dabei nutzen wir eine Liste mit bis zu $n$-Elementen als Datenstruktur, die am Index $i$ angibt, in welcher Reihe in der $i$-ten Spalte eine Dame platziert wurde. Aufgrund der Tatsache, dass eine Dame ihre komplette Spalte schlägt, ist trivial, dass sich in jeder Spalte nur eine Dame befinden kann. Da $n$ Damen auf $n$ Reihen verteilt werden, folgt, dass in jeder Spalte genau eine Dame stehen muss.

Die Liste [0, 4, 7, 5, 2, 6, 1, 3] beschreibt dabei folgende Stellung:

<img src="https://webinstitute.files.wordpress.com/2012/04/8-queens2.png?w=660" width="250">

Man fängt mit einem leeren Schachbrett an. Nun wird schrittweise in jeder Spalte eine Dame platziert werden. Dabei werden alle Reihen von 0 bis $n-1$ durchprobiert. Dies bedeutet, dass die Tiefensuche mit der entsprechenden Konfiguration aufgerufen wird. Es wird dabei geprüft, ob es sich bei der angegebenen Stellung noch um eine gültige Stellung handelt, d.h. keine Dame kann eine andere Dame schlagen. Ist dies der Fall, so wird weiter expandiert und in der nächsten Spalte der Algorithmus mit den den Reihen 0 bis $n-1$ rekursiv aufgerufen. Handelt es sich nicht um ein gültige Stellung, so wird eine leere Liste als Lösungsmenge zurückgegeben und der Computer macht - entsprechend nach dem Prinzip des Backtrackings - an der letzten Entscheidungsmöglichkeit weiter. Dies minimiert die Anzahl der zu überprüfenden Stellungen enorm, da - anders als bei einem Brute-Force Ansatz, bei dem alle Stellungen durchprobiert werden - nun auch alle folgenden Stellungen ausgeschlossen werden. 

In [165]:
def feasible(setting):
    if len(set(setting)) != len(setting):
        return False
    for i in range(len(setting)):
        for j in range(len(setting)):
            if j != i and (setting[j] == setting[i] - i + j or setting[j] == setting[i] + i - j):
                return False
    return True


def n_queens(n, setting=[]):
    if not feasible(setting):
        return []
    if len(setting) == n:
        return [list(setting)]
    solutions = []
    for i in range(n):
        solutions += n_queens(n, setting + [i])
    return solutions


print('Solutions of the 4 queens problem:', end=' ')
print(n_queens(4))
print('Number of solutions of the 8 queens problem:', end=' ')
print(len(n_queens(8)))

Solutions of the 4 queens problem: [[1, 3, 0, 2], [2, 0, 3, 1]]
Number of solutions of the 8 queens problem: 92


In [166]:
import numpy as np
import math


def contains_dupl(arr):
    elements = {}
    for elm in arr:
        if elm != 0:
            if elm in elements:
                return True
            elements[elm] = True
    return False


def contains_dupl_in_square(sudoku, x, y, n):
    elements = {}
    for i in range(x, x + n):
        for j in range(y, y + n):
            elm = sudoku.item(i, j)
            if elm != 0:
                if elm in elements:
                    return True
                elements[elm] = False
    return False


def feasible(sudoku, n=None):
    if n is None:
        n = sudoku.shape[0]
    for i in range(n):
        if contains_dupl(np.squeeze(np.asarray(sudoku[i, :]))) or contains_dupl(np.squeeze(np.asarray(sudoku[:, i]))):
            return False
    for i in range(0, n, int(math.sqrt(n))):
        for j in range(0, n, int(math.sqrt(n))):
            if contains_dupl_in_square(sudoku, i, j, int(math.sqrt(n))):
                return False
    return True


def solve(sudoku, n=None):
    if n is None:
        n = sudoku.shape[0]
    if not feasible(sudoku):
        return None
    for i in range(n):
        for j in range(n):
            if sudoku.item(i, j) == 0:
                for k in range(1, n+1):
                    new_sudoku = sudoku.copy()
                    new_sudoku[i, j] = k
                    solution = solve(new_sudoku, n)
                    if solution is not None:
                        return solution
                return None
    return sudoku


sudoku = np.matrix([[5,1,7,6,0,0,0,3,4],
                    [2,8,9,0,0,4,0,0,0],
                    [3,4,6,2,0,5,0,9,0],
                    [6,0,2,0,0,0,0,1,0],
                    [0,3,8,0,0,6,0,4,7],
                    [0,0,0,0,0,0,0,0,0],
                    [0,9,0,0,0,0,0,7,8],
                    [7,0,3,4,0,0,5,6,0],
                    [0,0,0,0,0,0,0,0,0]])

print(solve(sudoku))

[[5 1 7 6 9 8 2 3 4]
 [2 8 9 1 3 4 7 5 6]
 [3 4 6 2 7 5 8 9 1]
 [6 7 2 8 4 9 3 1 5]
 [1 3 8 5 2 6 9 4 7]
 [9 5 4 7 1 3 6 8 2]
 [4 9 5 3 6 2 1 7 8]
 [7 2 3 4 8 1 5 6 9]
 [8 6 1 9 5 7 4 2 3]]
