#### 1.
>   a)

In [22]:
def adjacent(a, b, visited=set()):
    if a == b:
        return True
    visited.add(a)
    for node in a.adj:
        if node not in visited and adjacent(node, b, set(visited)):
            return True
    return False

> b)
> $\mathcal{O}(\left| V \right| + \left| E \right|)$

#### 2.
>   a)

In [23]:
def reachable_nodes(root, visited=set()):
    reachable = set()
    reachable.add(root)
    visited.add(root)
    for node in root.adj:
        reachable_from_subnode = reachable_nodes(node, visited)
        for reachable_node in reachable_from_subnode:
            reachable.add(reachable_node)
    return reachable

> b)
> $\mathcal{O}(\left| V \right| + \left| E \right|)$

#### 3.
>   a)

In [24]:
import numpy as np
import math


def contains_dupl(arr):
    elements = {}
    for elm in arr:
        if elm != 0:
            if elm in elements:
                return True
            elements[elm] = True
    return False


def contains_dupl_in_square(sudoku, x, y, n):
    elements = {}
    for i in range(x, x + n):
        for j in range(y, y + n):
            elm = sudoku.item(i, j)
            if elm != 0:
                if elm in elements:
                    return True
                elements[elm] = False
    return False


def feasible(sudoku, n=None):
    if n is None:
        n = sudoku.shape[0]
    for i in range(n):
        if contains_dupl(np.squeeze(np.asarray(sudoku[i, :]))) or contains_dupl(np.squeeze(np.asarray(sudoku[:, i]))):
            return False
    for i in range(0, n, int(math.sqrt(n))):
        for j in range(0, n, int(math.sqrt(n))):
            if contains_dupl_in_square(sudoku, i, j, int(math.sqrt(n))):
                return False
    return True


def solve(sudoku, n=None):
    if n is None:
        n = sudoku.shape[0]
    if not feasible(sudoku):
        return None
    for i in range(n):
        for j in range(n):
            if sudoku.item(i, j) == 0:
                for k in range(1, n+1):
                    new_sudoku = sudoku.copy()
                    new_sudoku[i, j] = k
                    solution = solve(new_sudoku, n)
                    if solution is not None:
                        return solution
                return None
    return sudoku


sudoku = np.matrix([[5,1,7,6,0,0,0,3,4],
                    [2,8,9,0,0,4,0,0,0],
                    [3,4,6,2,0,5,0,9,0],
                    [6,0,2,0,0,0,0,1,0],
                    [0,3,8,0,0,6,0,4,7],
                    [0,0,0,0,0,0,0,0,0],
                    [0,9,0,0,0,0,0,7,8],
                    [7,0,3,4,0,0,5,6,0],
                    [0,0,0,0,0,0,0,0,0]])

print(solve(sudoku))

[[5 1 7 6 9 8 2 3 4]
 [2 8 9 1 3 4 7 5 6]
 [3 4 6 2 7 5 8 9 1]
 [6 7 2 8 4 9 3 1 5]
 [1 3 8 5 2 6 9 4 7]
 [9 5 4 7 1 3 6 8 2]
 [4 9 5 3 6 2 1 7 8]
 [7 2 3 4 8 1 5 6 9]
 [8 6 1 9 5 7 4 2 3]]


> b)
> $\mathcal{O}(n^{n^2})$

> bzw.

> $\mathcal{O}(n^m)$ mit $m$ = Anzahl der freien Felder